# vi: ft=nginx

### Config ###
# read more here https://gist.github.com/plentz/6737338

# config to don't allow the browser to render the page inside an frame or iframe
# and avoid clickjacking http://en.wikipedia.org/wiki/Clickjacking
# if you need to allow [i]frames, you can use SAMEORIGIN or even set an uri with ALLOW-FROM uri
# https://developer.mozilla.org/en-US/docs/HTTP/X-Frame-Options
add_header X-Frame-Options SAMEORIGIN always;

# when serving user-supplied content, include a X-Content-Type-Options: nosniff header along with the Content-Type: header,
# to disable content-type sniffing on some browsers.
# https://owasp.org/www-project-secure-headers/
add_header X-Content-Type-Options nosniff always;

# config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
# to avoid ssl stripping https://blog.cloudflare.com/performing-preventing-ssl-stripping-a-plain-english-primer/
# One year, the minimum accepted by https://hstspreload.org/
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# Do not leak the full URL of the referring page to other origins.
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
add_header Referrer-Policy "strict-origin-when-cross-origin" always;


# Set the correct IP addresses from cloudflare
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;

# Set the host from what's forwarded from cloudflare
proxy_set_header Host              $host;

# Set the protocol
proxy_set_header X-Forwarded-Proto $scheme;
