engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
        - javascript
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
    - app/**
    - bin/**
exclude_paths:
  - config/
  - app/static/css/bootstrap.css
  - app/static/css/normalize.css
  - app/static/css/tether.css
  - app/static/js/bootstrap.js
  - app/static/js/jquery.js
  - app/static/js/tether.js
